
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 09:10:59 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 32;
  public static final int GREATER_OR_EQUAL = 21;
  public static final int INCREMENT = 25;
  public static final int CHAR = 47;
  public static final int CONST = 7;
  public static final int NAMESPACE = 18;
  public static final int NOT_EQUAL = 20;
  public static final int LPAREN = 40;
  public static final int SEMI = 37;
  public static final int GREATER = 34;
  public static final int CONTINUE = 15;
  public static final int MULTIPY = 31;
  public static final int LESS = 35;
  public static final int FOR = 16;
  public static final int MINUS = 30;
  public static final int DECREMENT = 26;
  public static final int RPAREN = 41;
  public static final int STATIC = 17;
  public static final int AND = 23;
  public static final int LESS_OR_EQUAL = 22;
  public static final int OR = 24;
  public static final int BOOL = 49;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int PLUS = 29;
  public static final int MAIN = 6;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 19;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int NUMBER = 46;
  public static final int LSQUAREBRACE = 44;
  public static final int IDENT = 48;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int COLON = 38;
  public static final int LBRACE = 42;
  public static final int ELSE = 5;
  public static final int ACCESS = 28;
  public static final int READ = 11;
  public static final int ASSIGMNET = 36;
  public static final int RBRACE = 43;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int FULLSTOP = 27;
  public static final int RSQUAREBRACE = 45;
  public static final int MODUS = 33;
  public static final int PRINT = 10;
}

